### ISSUE TITLE
gk_cli crashes in python3 when creating entities

### ISSUE THREAD

**Issue by tshastry** [finos-voice/greenkey-discovery-sdk#23]
```
? Do you need any additional custom tokens for your entity?  No
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gk_cli", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gk_cli/__main__.py", line 114, in main
    return create_new_project('custom/')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gk_cli/__main__.py", line 139, in create_new_project
    create_new_entity(file_location + 'entities/', entity)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gk_cli/entity.py", line 22, in create_new_entity
    _create_new_entity_file(entity_name_choice, custom_tokens, file_location)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gk_cli/entity.py", line 27, in _create_new_entity_file
    file_content = _get_file_content(entity_name, custom_tokens)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gk_cli/entity.py", line 38, in _get_file_content
    entity_definition_content = _get_entity_definition_content(entity_name, custom_tokens)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gk_cli/entity.py", line 97, in _get_entity_definition_content
    'extraTokens': ''' + _format_custom_tokens(custom_tokens) + ','
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gk_cli/entity.py", line 110, in _format_custom_tokens
    return str(tuple([remove_quotation_marks(token['label']) for token in custom_tokens])).replace("'", '')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gk_cli/entity.py", line 110, in <listcomp>
    return str(tuple([remove_quotation_marks(token['label']) for token in custom_tokens])).replace("'", '')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gk_cli/cli_utils.py", line 71, in remove_quotation_marks
    return string.replace('"', '').strip("\'")
TypeError: a bytes-like object is required, not 'str'

```

**Comment by AGiantSquid** [comment]
This should be fixed with https://github.com/finos-voice/greenkey-discovery-sdk/commit/bb27efc991b62fdf51d5c405760f88eb8a083c55
